apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-api-hpa
  namespace: tembici-app
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: app-api
  targetCPUUtilizationPercentage: 80

