apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: app-api
  name: app-api
  namespace: tembici-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxSurge: 4
     maxUnavailable: 0
  selector:
    matchLabels:
      run: app-api
  template:
    metadata:
      labels:
        run: app-api
    spec:
      containers:
      - imagePullPolicy: Always
        image: us-central1-docker.pkg.dev/sixth-emissary-359700/app-registry/api:latest
        name: app-api
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "400m"          
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerhub
status: {}
