apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  namespace: tembici-app
spec:
  selector:
    matchLabels:
      app: app-api
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: app-api
    spec:
#      imagePullSecrets:
#      - name: artifact-registry      
      containers:
      - name: app-api
        image: us-central1-docker.pkg.dev/sixth-emissary-359700/app-registry/api:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
