apiVersion: v1
kind: Service
metadata:
  name: app-api-service
  namespace: tembici-app
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    run: app-api
  type: LoadBalancer
status:
  loadBalancer: {}
