name: "Build, push and deploy docker images"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-push-image:
    env: 
      IMAGE_NAME: api
      REGISTRY: app-registry
      PROJECT_ID: sixth-emissary-359700
      ARTIFACTORY_REGISTRY_URL: us-central1-docker.pkg.dev
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 
    name: build and push image to Registry
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: auth
        uses: google-github-actions/auth@v0
        with: 
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS}}   

      - name: Using Gcloud SDK
        uses: google-github-actions/setup-gcloud@v0
      
      - name: Build docker 
        #run: docker build -t $IMAGE_NAME:latest . 
        run: docker build -t us-central1-docker.pkg.dev/sixth-emissary-359700/app-registry/api:latest --no-cache .

      - name: Build and push Image to Registry
        #run: docker push $ARTIFACTORY_REGISTRY_URL/$PROJECT_ID/$REGISTRY/$IMAGE_NAME:latest
        run: docker push us-central1-docker.pkg.dev/sixth-emissary-359700/app-registry/api:latest






