name: "Build, push and deploy docker images"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-push-image:
    env: 
      IMAGE_NAME: api
      REGISTRY: app-registry
      PROJECT_ID: sixth-emissary-359700
      ARTIFACTORY_REGISTRY_URL: us-central1-docker.pkg.dev
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 
    name: build and push image to Registry
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud
        with: 
          service_account_key: ${{secrets.GOOGLE_CREDENTIALS}}
          project_id: ${{env.PROJECT_ID}}
          export_default_credentials: true
      
      - name: Build docker 
        run: docker build -t $IMAGE_NAME:latest . 

      - name: Configure docker
        run: |-
          gcloud auth configure-docker --quiet

      - name: Build and push Image to Registry
        run: |-
          docker push $ARTIFACTORY_REGISTRY_URL/$PROJECT_ID/$REGISTRY/$IMAGE:latest






