name: "Terraform build GKE"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-image:
    env: 
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 
    name: build-image
    runs-on: ubuntu-latest
    #needs: terraform

    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - id: build-docker-image
        run: docker build --network=host -t us-central1-docker.pkg.dev/sixth-emissary-359700/app-registry/api:latest --no-cache .

      - id: authenticate
        run: base64 $GOOGLE_CREDENTIALS | docker login -u _json_key_base64 --password-stdin https://us-central1-docker.pkg.dev  

      - id: push-image-to-registry
        run: docker push us-central1-docker.pkg.dev/sixth-emissary-359700/app-registry/api:latest 
