name: "Terraform build GKE"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-image: 
    name: build-image
    runs-on: ubuntu-latest
    #needs: terraform

    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - id: build-docker-image
        run: docker build -t us-central1-docker.pkg.dev/sixth-emissary-359700/app-registry/api:latest --no-cache . 
